### ISSUE TITLE
Stream #7 ToDo List

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#141]
ToDo:
* [x] Highlight LOC
* [x] Highlight contributors / PRs
* [x] Right
* [x] Off stream lessons learned
* [x] Set up `p.ijs`?
* [x] Port `right`
* [ ] ~~Code removal~~
