### ISSUE TITLE
LiveStream #11 ToDO

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#196]
### ToDo 

* [x] Close / review / merge several PRs
* [x] Set up auto-assign for `aal`
* [x] `Softmax` in J
* [ ] ~~Add `_if` to our `find` algorithm~~
* [x] Write `aal::var::transform`
* [x] Use this in `take_and_drop.hpp`
