### ISSUE TITLE
LiveStream #12 ToDo List

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#211]
Link https://youtu.be/RnuwbsjGFYE

* [x] Review https://github.com/codereport/An-Algorithm-Library/issues/5#issuecomment-792293274
* [x] Fix https://github.com/codereport/jsource/issues/206
* [x] Review https://github.com/codereport/jsource/pull/200 (first 1/3)
* [x] Review https://github.com/codereport/jsource/pull/208
