### ISSUE TITLE
TODO on Next Stream (#5):

### ISSUE THREAD

**Issue by codereport** [codereport/jsource#70]
## When:
* Saturday January 30th 12:00 PM EST 
* Link: https://youtu.be/fvzZ2DkmHlY
## To Do:
* [x] Highlight:
   * [x] Contributors (insights)
   * [x] Removals
   * [x] Folder restruction
   * [x] JHS Server
* [x] Set up Github Actions: https://github.com/marketplace/actions/auto-assign-action
* [x] TALLY! (still lots to do - I will open issues to track)
* [ ] SHAPE!
* [x] Explore C++ doc options
   * [x] [Doxygen](https://www.doxygen.nl/index.html)
   * [x] [Doxygen + Sphinx/Breathe](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/)
   * [x] [standardese](https://github.com/standardese/standardese)
   * [x] I want something that looks closest to [HexDocs](https://hexdocs.pm/elixir/Enum.html#all?/2)
